import {articles as fallbackArticles, brands as fallbackBrands, homepage as fallbackHomepage, navigation as fallbackNavigation, services as fallbackServices, siteSettings as fallbackSettings, toolkits as fallbackToolkits, videoGalleries as fallbackVideos} from '@/data/fallback'
import type {AboutPage, Article, Author, Brand, CosmeticPrPage, DiamondAwards, Founder, Homepage, HomeSectionType, ImageValue, MediaDesk, MediaHubPage, MegaMenuContent, MembershipPage, MenuLink, Navigation, PortableTextBlock, Principle, SEO, Service, SiteSettings, Stat, Toolkit, VideoGallery, VideoPage} from '@/types'
import {sanityFetch} from '@/sanity/lib/fetch'
import {ABOUT_PAGE_QUERY, ARTICLE_QUERY, ARTICLES_QUERY, BRANDS_QUERY, COSMETIC_PR_PAGE_QUERY, FOUNDER_QUERY, HOMEPAGE_QUERY, MEDIA_DESK_QUERY, MEDIA_HUB_QUERY, VIDEO_PAGE_QUERY, MEMBERSHIP_PAGE_QUERY, NAVIGATION_QUERY, SERVICE_QUERY, SERVICES_QUERY, SITE_SETTINGS_QUERY, TOOLKITS_QUERY, DIAMOND_AWARDS_QUERY, VIDEOS_QUERY, VIDEO_QUERY} from '@/sanity/lib/queries'
import type {ABOUT_PAGE_QUERY_RESULT, ARTICLE_QUERY_RESULT, ARTICLES_QUERY_RESULT, BRANDS_QUERY_RESULT, COSMETIC_PR_PAGE_QUERY_RESULT, DIAMOND_AWARDS_QUERY_RESULT, FOUNDER_QUERY_RESULT, HOMEPAGE_QUERY_RESULT, MEDIA_DESK_QUERY_RESULT, MEDIA_HUB_QUERY_RESULT, VIDEO_PAGE_QUERY_RESULT, MEMBERSHIP_PAGE_QUERY_RESULT, SERVICE_QUERY_RESULT, SERVICES_QUERY_RESULT, SITE_SETTINGS_QUERY_RESULT, TOOLKITS_QUERY_RESULT} from '../../sanity.types'

/**
 * This module is the single translation boundary between Sanity and the app.
 *
 * `sanityFetch` returns types generated by Sanity TypeGen (`sanity.types.ts`),
 * which mirror the wire format: every projected field is nullable and images
 * carry the raw asset shape. The mappers below normalise that into the app
 * domain types (`@/types`) the components consume, coalescing nulls and applying
 * local fallback content. Keeping the mapping here means the query projections
 * are type-checked against the schema without leaking `| null` into every view.
 */

// Permissive inputs: the generated per-query result types are all assignable to
// these, so one mapper can accept a field whether it came from a list, detail or
// homepage projection.
type ImageInput =
  | {asset?: {_id?: string; _ref?: string | null; url?: string | null} | null; alt?: string}
  | null
  | undefined

type SeoInput =
  | {metaTitle?: string; metaDescription?: string; ogImage?: ImageInput; noIndex?: boolean}
  | null
  | undefined

type StatInput = {value?: string; numericValue?: number; suffix?: string; label?: string; note?: string}

type AuthorInput =
  | {name?: string | null; slug?: string | null; role?: string | null; bio?: string | null; image?: ImageInput}
  | null
  | undefined

type ArticleInput = {
  _id?: string
  title?: string | null
  slug?: string | null
  excerpt?: string | null
  category?: string | null
  format?: Article['format'] | null
  publishedAt?: string | null
  readingTime?: string | null
  featured?: boolean | null
  externalVideoUrl?: string | null
  tags?: Array<string> | null
  image?: ImageInput
  author?: AuthorInput
  body?: unknown
  relatedService?: {title?: string | null; slug?: string | null} | null
  seo?: SeoInput
}

type ServiceInput = {
  _id?: string
  title?: string | null
  slug?: string | null
  eyebrow?: string | null
  intro?: string | null
  listDescription?: string | null
  listCta?: string | null
  detailIntro?: string | null
  body?: string | null
  outcomes?: Array<string> | null
  deliverables?: Array<string> | null
  image?: ImageInput
  seo?: SeoInput
}

type BrandInput = {
  title?: string | null
  slug?: string | null
  type?: string | null
  description?: string | null
  href?: string | null
  external?: boolean | null
  ctaLabel?: string | null
  image?: ImageInput
}

type ToolkitInput = {
  title?: string | null
  slug?: string | null
  type?: string | null
  description?: string | null
  access?: Toolkit['access'] | null
  coverStyle?: Toolkit['coverStyle'] | null
  fileUrl?: string | null
}

// Field helpers --------------------------------------------------------------

function toImage(src: ImageInput): ImageValue | undefined {
  if (!src?.asset) return undefined
  const {_id, _ref, url} = src.asset
  return {
    asset: {...(_id ? {_id} : {}), ...(_ref ? {_ref} : {}), ...(url ? {url} : {})},
    alt: src.alt
  }
}

function toPortableText(value: unknown): PortableTextBlock[] | undefined {
  return Array.isArray(value) && value.length ? (value as PortableTextBlock[]) : undefined
}

function toStats(src: Array<StatInput> | null | undefined): Stat[] | undefined {
  return src?.map((s) => ({value: s.value ?? '', numericValue: s.numericValue, suffix: s.suffix, label: s.label ?? '', note: s.note}))
}

function toPrinciples(src: Array<{title?: string; description?: string}> | null | undefined): Principle[] | undefined {
  return src?.map((p) => ({title: p.title ?? '', description: p.description ?? ''}))
}

function toSeo(src: SeoInput): SEO | undefined {
  if (!src) return undefined
  return {metaTitle: src.metaTitle, metaDescription: src.metaDescription, ogImage: toImage(src.ogImage), noIndex: src.noIndex}
}

// Entity mappers -------------------------------------------------------------

function toAuthor(src: AuthorInput): Author | undefined {
  if (!src) return undefined
  return {name: src.name ?? '', slug: src.slug ?? undefined, role: src.role ?? undefined, bio: src.bio ?? undefined, image: toImage(src.image)}
}

function toArticle(a: ArticleInput): Article {
  return {
    _id: a._id,
    title: a.title ?? '',
    slug: a.slug ?? '',
    excerpt: a.excerpt ?? '',
    category: a.category ?? '',
    format: a.format ?? undefined,
    publishedAt: a.publishedAt ?? '',
    readingTime: a.readingTime ?? undefined,
    image: toImage(a.image),
    author: toAuthor(a.author),
    body: toPortableText(a.body),
    externalVideoUrl: a.externalVideoUrl ?? undefined,
    featured: a.featured ?? undefined,
    tags: a.tags ?? undefined,
    relatedService: a.relatedService ? {title: a.relatedService.title ?? '', slug: a.relatedService.slug ?? ''} : undefined,
    seo: toSeo(a.seo)
  }
}

type VideoGalleryInput = {
  title?: string | null
  slug?: string | null
  category?: string | null
  intro?: string | null
  order?: number | null
  poster?: ImageInput
  videos?: Array<{heading?: string | null; url?: string | null; caption?: string | null}> | null
  seo?: SeoInput
}

function toVideoGallery(v: VideoGalleryInput): VideoGallery {
  return {
    title: v.title ?? '',
    slug: v.slug ?? '',
    category: v.category ?? undefined,
    intro: v.intro ?? undefined,
    order: v.order ?? undefined,
    poster: toImage(v.poster),
    videos: (v.videos ?? [])
      .map((item) => ({heading: item.heading ?? undefined, url: item.url ?? undefined, caption: item.caption ?? undefined}))
      .filter((item) => Boolean(item.url)),
    seo: toSeo(v.seo)
  }
}

function toService(s: ServiceInput): Service {
  return {
    _id: s._id,
    title: s.title ?? '',
    slug: s.slug ?? '',
    eyebrow: s.eyebrow ?? '',
    intro: s.intro ?? '',
    listDescription: s.listDescription ?? undefined,
    listCta: s.listCta ?? undefined,
    detailIntro: s.detailIntro ?? undefined,
    body: s.body ?? '',
    image: toImage(s.image),
    deliverables: s.deliverables ?? [],
    outcomes: s.outcomes ?? [],
    seo: toSeo(s.seo)
  }
}

function toBrand(b: BrandInput): Brand {
  return {
    title: b.title ?? '',
    slug: b.slug ?? '',
    type: b.type ?? '',
    description: b.description ?? '',
    image: toImage(b.image),
    href: b.href ?? undefined,
    external: b.external ?? undefined,
    ctaLabel: b.ctaLabel ?? undefined
  }
}

function toToolkit(t: ToolkitInput): Toolkit {
  return {
    title: t.title ?? '',
    slug: t.slug ?? '',
    type: t.type ?? '',
    description: t.description ?? '',
    access: t.access ?? 'comingSoon',
    coverStyle: t.coverStyle ?? undefined,
    fileUrl: t.fileUrl ?? undefined
  }
}

// Loaders --------------------------------------------------------------------

export async function getSiteSettings(): Promise<SiteSettings> {
  const data = await sanityFetch<SITE_SETTINGS_QUERY_RESULT>(SITE_SETTINGS_QUERY)
  if (!data) return fallbackSettings
  return {
    title: data.title ?? fallbackSettings.title,
    tagline: data.tagline ?? fallbackSettings.tagline,
    description: data.description ?? fallbackSettings.description,
    email: data.email ?? fallbackSettings.email,
    phone: data.phone ?? fallbackSettings.phone,
    locations: data.locations ?? fallbackSettings.locations,
    logo: toImage(data.logo) ?? fallbackSettings.logo,
    socialLinks: data.socialLinks?.map((l) => ({platform: l.platform ?? '', url: l.url ?? ''})) ?? fallbackSettings.socialLinks,
    legalLinks: data.legalLinks?.map((l) => ({label: l.label ?? '', url: l.url ?? ''})) ?? fallbackSettings.legalLinks
  }
}

export async function getHomepage(): Promise<Homepage> {
  const data = await sanityFetch<HOMEPAGE_QUERY_RESULT>(HOMEPAGE_QUERY)
  if (!data) return fallbackHomepage
  const storedOrder = (data.sections || [])
    .filter((x) => x.enabled !== false)
    .map((x) => x.sectionType)
    .filter((t): t is HomeSectionType => Boolean(t))
  // V19 migration shim: a stored order that predates the Cosmetic PR spotlight
  // section is superseded by the approved V19 order until the dataset is reseeded
  // (or an editor re-saves the section list including it).
  const sectionOrder = storedOrder.length && storedOrder.includes('cprSpotlight') ? storedOrder : fallbackHomepage.sectionOrder
  const stats = toStats(data.stats)
  return {
    hero: {
      eyebrowLeft: data.heroEyebrowLeft || fallbackHomepage.hero.eyebrowLeft,
      eyebrowRight: data.heroEyebrowRight || fallbackHomepage.hero.eyebrowRight,
      titleBefore: data.heroTitleBefore || fallbackHomepage.hero.titleBefore,
      titleAccent: data.heroTitleAccent || fallbackHomepage.hero.titleAccent,
      identity: data.heroIdentity || fallbackHomepage.hero.identity,
      summary: data.heroSummary || fallbackHomepage.hero.summary,
      image: toImage(data.heroImage) || fallbackHomepage.hero.image,
      imageCaption: data.heroImageCaption || fallbackHomepage.hero.imageCaption,
      imageMeta: data.heroImageMeta || fallbackHomepage.hero.imageMeta,
      film: data.heroFilm?.length ? data.heroFilm.map(toImage).filter((img): img is ImageValue => Boolean(img)) : fallbackHomepage.hero.film,
      videoUrl: data.heroVideoUrl ?? fallbackHomepage.hero.videoUrl,
      filmBadge: data.heroFilmBadge || fallbackHomepage.hero.filmBadge,
      primaryCta: fallbackHomepage.hero.primaryCta,
      secondaryCta: fallbackHomepage.hero.secondaryCta
    },
    sectionOrder,
    story: {
      heading: data.storyHeading || fallbackHomepage.story?.heading,
      opening: data.storyOpening || fallbackHomepage.story?.opening,
      body: toPortableText(data.storyBody) ?? fallbackHomepage.story?.body
    },
    stats: stats?.length ? stats : fallbackHomepage.stats,
    credibilityFacts: data.credibilityFacts?.length ? data.credibilityFacts.map((f) => ({label: f.label ?? '', title: f.title ?? ''})) : fallbackHomepage.credibilityFacts,
    publications: data.publications?.length ? data.publications : fallbackHomepage.publications,
    clientLogos: data.clientLogos?.length ? data.clientLogos.map((l) => ({name: l.name ?? '', image: toImage(l.image)})) : fallbackHomepage.clientLogos,
    latestRail: data.latestRail?.length
      ? data.latestRail.flatMap((item) => (item.label && item.title ? [{label: item.label, title: item.title, actionLabel: item.actionLabel ?? undefined, href: item.href ?? undefined}] : []))
      : fallbackHomepage.latestRail,
    brandRail: data.brandRail?.length
      ? data.brandRail.flatMap((item) => (item.label && item.title ? [{label: item.label, title: item.title, description: item.description ?? undefined, href: item.href ?? undefined}] : []))
      : fallbackHomepage.brandRail,
    resourceTiles: data.resourceTiles?.length
      ? data.resourceTiles.flatMap((item) => (item.title ? [{tag: item.tag ?? undefined, title: item.title, actionLabel: item.actionLabel ?? undefined, href: item.href ?? undefined}] : []))
      : fallbackHomepage.resourceTiles,
    cprSpotlight: (data.cprHeading || data.cprCards?.length)
      ? {
          eyebrow: data.cprEyebrow ?? undefined,
          heading: data.cprHeading ?? undefined,
          accent: data.cprAccent ?? undefined,
          intro: data.cprIntro ?? undefined,
          statusChips: data.cprStatusChips ?? undefined,
          cards: (data.cprCards || []).flatMap((card) =>
            card.title ? [{label: card.label ?? undefined, title: card.title, text: card.text ?? undefined, ctaLabel: card.ctaLabel ?? undefined, image: toImage(card.image)}] : []
          )
        }
      : fallbackHomepage.cprSpotlight,
    featuredArticles: data.featuredArticles?.map(toArticle) ?? [],
    featuredServices: data.featuredServices?.map(toService) ?? [],
    featuredBrands: data.featuredBrands?.map(toBrand) ?? [],
    featuredToolkits: data.featuredToolkits?.map(toToolkit) ?? [],
    seo: toSeo(data.seo)
  }
}

export async function getServices(): Promise<Service[]> {
  const data = await sanityFetch<SERVICES_QUERY_RESULT>(SERVICES_QUERY)
  return data?.length ? data.map(toService) : fallbackServices
}

export async function getService(slug: string): Promise<Service | null> {
  const data = await sanityFetch<SERVICE_QUERY_RESULT>(SERVICE_QUERY, {slug})
  return data ? toService(data) : fallbackServices.find((service) => service.slug === slug) || null
}

export async function getArticles(): Promise<Article[]> {
  const data = await sanityFetch<ARTICLES_QUERY_RESULT>(ARTICLES_QUERY)
  return data?.length ? data.map(toArticle) : fallbackArticles
}

export async function getArticle(slug: string): Promise<Article | null> {
  const data = await sanityFetch<ARTICLE_QUERY_RESULT>(ARTICLE_QUERY, {slug})
  return data ? toArticle(data) : fallbackArticles.find((article) => article.slug === slug) || null
}

type RawMenuLink = {label?: string | null; page?: string | null; externalUrl?: string | null; service?: {title?: string | null; slug?: string | null} | null}
type MegaInput = {eyebrow?: string | null; heading?: string | null; text?: string | null; ctaLabel?: string | null; ctaHref?: string | null; links?: Array<RawMenuLink> | null} | null | undefined
type NavigationInput = {about?: MegaInput; services?: MegaInput} | null

function toMega(src: MegaInput, fallback: MegaMenuContent): MegaMenuContent {
  return {
    eyebrow: src?.eyebrow ?? fallback.eyebrow,
    heading: src?.heading ?? fallback.heading,
    text: src?.text ?? fallback.text,
    ctaLabel: src?.ctaLabel ?? fallback.ctaLabel,
    ctaHref: src?.ctaHref ?? fallback.ctaHref
  }
}

function resolveMenuLinks(raw: Array<RawMenuLink> | null | undefined): MenuLink[] {
  return (raw ?? [])
    .map((link) => ({
      label: (link.label ?? '').trim() || (link.service?.title ?? ''),
      href: (link.externalUrl ?? '').trim() || (link.service?.slug ? `/services/${link.service.slug}` : (link.page ?? ''))
    }))
    .filter((link) => link.label && link.href)
}

export async function getNavigation(): Promise<Navigation> {
  const data = await sanityFetch<NavigationInput>(NAVIGATION_QUERY)
  if (!data) return fallbackNavigation
  const aboutLinks = resolveMenuLinks(data.about?.links)
  return {
    about: {...toMega(data.about, fallbackNavigation.about), links: aboutLinks.length ? aboutLinks : fallbackNavigation.about.links},
    services: {...toMega(data.services, fallbackNavigation.services), links: resolveMenuLinks(data.services?.links)}
  }
}

export async function getVideos(): Promise<VideoGallery[]> {
  const data = await sanityFetch<VideoGalleryInput[]>(VIDEOS_QUERY)
  return data?.length ? data.map(toVideoGallery) : fallbackVideos
}

export async function getVideo(slug: string): Promise<VideoGallery | null> {
  const data = await sanityFetch<VideoGalleryInput>(VIDEO_QUERY, {slug})
  return data ? toVideoGallery(data) : fallbackVideos.find((video) => video.slug === slug) || null
}

export async function getBrands(): Promise<Brand[]> {
  const data = await sanityFetch<BRANDS_QUERY_RESULT>(BRANDS_QUERY)
  return data?.length ? data.map(toBrand) : fallbackBrands
}

export async function getToolkits(): Promise<Toolkit[]> {
  const data = await sanityFetch<TOOLKITS_QUERY_RESULT>(TOOLKITS_QUERY)
  return data?.length ? data.map(toToolkit) : fallbackToolkits
}

export async function getAboutPage(): Promise<AboutPage | null> {
  const data = await sanityFetch<ABOUT_PAGE_QUERY_RESULT>(ABOUT_PAGE_QUERY)
  if (!data) return null
  return {
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    stats: toStats(data.stats),
    evolutionEyebrow: data.evolutionEyebrow ?? undefined,
    evolutionHeading: data.evolutionHeading ?? undefined,
    evolutionBody: toPortableText(data.evolutionBody),
    quote: data.quote ?? undefined,
    closingNote: data.closingNote ?? undefined,
    image: toImage(data.image),
    principlesEyebrow: data.principlesEyebrow ?? undefined,
    principlesHeading: data.principlesHeading ?? undefined,
    principlesIntro: data.principlesIntro ?? undefined,
    principles: toPrinciples(data.principles),
    seo: toSeo(data.seo)
  }
}

export async function getCosmeticPr(): Promise<CosmeticPrPage | null> {
  const data = await sanityFetch<COSMETIC_PR_PAGE_QUERY_RESULT>(COSMETIC_PR_PAGE_QUERY)
  if (!data) return null
  return {
    heroEyebrow: data.heroEyebrow ?? undefined,
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    heroIntro: data.heroIntro ?? undefined,
    heroBody: data.heroBody ?? undefined,
    heroImage: toImage(data.heroImage),
    heroCaption: data.heroCaption ?? undefined,
    heroCaptionMeta: data.heroCaptionMeta ?? undefined,
    identityStrip: (data.identityStrip || []).flatMap((item) => (item.label && item.value ? [{label: item.label, value: item.value}] : [])),
    storyEyebrow: data.storyEyebrow ?? undefined,
    storySideHeading: data.storySideHeading ?? undefined,
    storySideText: data.storySideText ?? undefined,
    storyHeading: data.storyHeading ?? undefined,
    storyAccent: data.storyAccent ?? undefined,
    storyBody: toPortableText(data.storyBody),
    capabilitiesEyebrow: data.capabilitiesEyebrow ?? undefined,
    capabilitiesNote: data.capabilitiesNote ?? undefined,
    capabilitiesHeading: data.capabilitiesHeading ?? undefined,
    capabilities: toPrinciples(data.capabilities),
    casesEyebrow: data.casesEyebrow ?? undefined,
    casesHeading: data.casesHeading ?? undefined,
    cases: (data.cases || []).flatMap((item) =>
      item.title ? [{label: item.label ?? undefined, title: item.title, description: item.description ?? undefined, tags: item.tags ?? undefined}] : []
    ),
    testimonialsEyebrow: data.testimonialsEyebrow ?? undefined,
    testimonialsHeading: data.testimonialsHeading ?? undefined,
    testimonials: (data.testimonials || []).flatMap((item) => (item.name && item.quote ? [{name: item.name, quote: item.quote}] : [])),
    publicationsEyebrow: data.publicationsEyebrow ?? undefined,
    publicationsHeading: data.publicationsHeading ?? undefined,
    publicationsIntro: data.publicationsIntro ?? undefined,
    publications: data.publications ?? undefined,
    summaryEyebrow: data.summaryEyebrow ?? undefined,
    summaryHeading: data.summaryHeading ?? undefined,
    summaryBody: toPortableText(data.summaryBody),
    summaryPoints: (data.summaryPoints || []).flatMap((item) => (item.label && item.text ? [{label: item.label, text: item.text}] : [])),
    newsletterEyebrow: data.newsletterEyebrow ?? undefined,
    newsletterHeading: data.newsletterHeading ?? undefined,
    newsletterText: data.newsletterText ?? undefined,
    seo: toSeo(data.seo)
  }
}

export async function getMembership(): Promise<MembershipPage | null> {
  const data = await sanityFetch<MEMBERSHIP_PAGE_QUERY_RESULT>(MEMBERSHIP_PAGE_QUERY)
  if (!data) return null
  return {
    comingSoonLabel: data.comingSoonLabel ?? undefined,
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    benefitsEyebrow: data.benefitsEyebrow ?? undefined,
    benefitsHeading: data.benefitsHeading ?? undefined,
    benefitsIntro: data.benefitsIntro ?? undefined,
    benefits: toPrinciples(data.benefits),
    seo: toSeo(data.seo)
  }
}

export async function getFounder(): Promise<Founder | null> {
  const data = await sanityFetch<FOUNDER_QUERY_RESULT>(FOUNDER_QUERY)
  if (!data) return null
  return {
    name: data.name ?? undefined,
    headline: data.headline ?? undefined,
    intro: data.intro ?? undefined,
    image: toImage(data.image),
    body: toPortableText(data.body),
    belief: data.belief ?? undefined,
    stats: toStats(data.stats),
    statsNote: data.statsNote ?? undefined,
    publications: data.publications ?? undefined,
    roles: toPrinciples(data.roles),
    seo: toSeo(data.seo)
  }
}

export async function getMediaDesk(): Promise<MediaDesk | null> {
  const data = await sanityFetch<MEDIA_DESK_QUERY_RESULT>(MEDIA_DESK_QUERY)
  if (!data) return null
  return {
    headline: data.headline ?? undefined,
    intro: data.intro ?? undefined,
    requestTypes: toPrinciples(data.requestTypes),
    futureResources: toPrinciples(data.futureResources),
    seo: toSeo(data.seo)
  }
}

export async function getMediaHubPage(): Promise<MediaHubPage | null> {
  const data = await sanityFetch<MEDIA_HUB_QUERY_RESULT>(MEDIA_HUB_QUERY)
  if (!data) return null
  return {
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    ctaEyebrow: data.ctaEyebrow ?? undefined,
    ctaHeading: data.ctaHeading ?? undefined,
    ctaText: data.ctaText ?? undefined,
    ctaButtonLabel: data.ctaButtonLabel ?? undefined,
    ctaButtonHref: data.ctaButtonHref ?? undefined,
    seo: toSeo(data.seo)
  }
}

export async function getVideoPage(): Promise<VideoPage | null> {
  const data = await sanityFetch<VIDEO_PAGE_QUERY_RESULT>(VIDEO_PAGE_QUERY)
  if (!data) return null
  return {
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    ctaEyebrow: data.ctaEyebrow ?? undefined,
    ctaHeading: data.ctaHeading ?? undefined,
    ctaText: data.ctaText ?? undefined,
    ctaButtonLabel: data.ctaButtonLabel ?? undefined,
    ctaButtonHref: data.ctaButtonHref ?? undefined,
    seo: toSeo(data.seo)
  }
}

export async function getDiamondAwards(): Promise<DiamondAwards | null> {
  const data = await sanityFetch<DIAMOND_AWARDS_QUERY_RESULT>(DIAMOND_AWARDS_QUERY)
  if (!data) return null
  return {
    eventName: data.eventName ?? undefined,
    date: data.date ?? undefined,
    venue: data.venue ?? undefined,
    location: data.location ?? undefined,
    heroImage: toImage(data.heroImage),
    historyImage: toImage(data.historyImage),
    missionImage: toImage(data.missionImage),
    whyDubaiImage: toImage(data.whyDubaiImage),
    sponsorImage: toImage(data.sponsorImage),
    experienceImage: toImage(data.experienceImage),
    contactImage: toImage(data.contactImage),
    missionPoints: data.missionPoints ?? undefined,
    audience: data.audience ?? undefined,
    eventExperience: data.eventExperience ?? undefined,
    sponsorBenefits: data.sponsorBenefits ?? undefined,
    sponsorshipPackages: data.sponsorshipPackages?.map((p) => ({tier: p.tier, name: p.name ?? '', description: p.description, features: p.features})),
    contactEmail: data.contactEmail ?? undefined,
    contactPhoneUae: data.contactPhoneUae ?? undefined,
    contactPhoneUk: data.contactPhoneUk ?? undefined,
    seo: toSeo(data.seo)
  }
}
