import {articles as fallbackArticles, brands as fallbackBrands, homepage as fallbackHomepage, services as fallbackServices, siteSettings as fallbackSettings, toolkits as fallbackToolkits} from '@/data/fallback'
import type {AboutPage, Article, Author, Brand, DiamondAwards, Founder, Homepage, HomeSectionType, ImageValue, MediaDesk, MembershipPage, PortableTextBlock, Principle, SEO, Service, SiteSettings, Stat, Toolkit} from '@/types'
import {sanityFetch} from '@/sanity/lib/fetch'
import {ABOUT_PAGE_QUERY, ARTICLE_QUERY, ARTICLES_QUERY, BRANDS_QUERY, FOUNDER_QUERY, HOMEPAGE_QUERY, MEDIA_DESK_QUERY, MEMBERSHIP_PAGE_QUERY, SERVICE_QUERY, SERVICES_QUERY, SITE_SETTINGS_QUERY, TOOLKITS_QUERY, DIAMOND_AWARDS_QUERY} from '@/sanity/lib/queries'
import type {ABOUT_PAGE_QUERY_RESULT, ARTICLE_QUERY_RESULT, ARTICLES_QUERY_RESULT, BRANDS_QUERY_RESULT, DIAMOND_AWARDS_QUERY_RESULT, FOUNDER_QUERY_RESULT, HOMEPAGE_QUERY_RESULT, MEDIA_DESK_QUERY_RESULT, MEMBERSHIP_PAGE_QUERY_RESULT, SERVICE_QUERY_RESULT, SERVICES_QUERY_RESULT, SITE_SETTINGS_QUERY_RESULT, TOOLKITS_QUERY_RESULT} from '../../sanity.types'

/**
 * This module is the single translation boundary between Sanity and the app.
 *
 * `sanityFetch` returns types generated by Sanity TypeGen (`sanity.types.ts`),
 * which mirror the wire format: every projected field is nullable and images
 * carry the raw asset shape. The mappers below normalise that into the app
 * domain types (`@/types`) the components consume, coalescing nulls and applying
 * local fallback content. Keeping the mapping here means the query projections
 * are type-checked against the schema without leaking `| null` into every view.
 */

// Permissive inputs: the generated per-query result types are all assignable to
// these, so one mapper can accept a field whether it came from a list, detail or
// homepage projection.
type ImageInput =
  | {asset?: {_id?: string; _ref?: string | null; url?: string | null} | null; alt?: string}
  | null
  | undefined

type SeoInput =
  | {metaTitle?: string; metaDescription?: string; ogImage?: ImageInput; noIndex?: boolean}
  | null
  | undefined

type StatInput = {value?: string; numericValue?: number; suffix?: string; label?: string; note?: string}

type AuthorInput =
  | {name?: string | null; slug?: string | null; role?: string | null; bio?: string | null; image?: ImageInput}
  | null
  | undefined

type ArticleInput = {
  _id?: string
  title?: string | null
  slug?: string | null
  excerpt?: string | null
  category?: string | null
  format?: Article['format'] | null
  publishedAt?: string | null
  readingTime?: string | null
  featured?: boolean | null
  externalVideoUrl?: string | null
  tags?: Array<string> | null
  image?: ImageInput
  author?: AuthorInput
  body?: unknown
  relatedService?: {title?: string | null; slug?: string | null} | null
  seo?: SeoInput
}

type ServiceInput = {
  _id?: string
  title?: string | null
  slug?: string | null
  eyebrow?: string | null
  intro?: string | null
  body?: string | null
  outcomes?: Array<string> | null
  deliverables?: Array<string> | null
  image?: ImageInput
  seo?: SeoInput
}

type BrandInput = {
  title?: string | null
  slug?: string | null
  type?: string | null
  description?: string | null
  href?: string | null
  external?: boolean | null
  image?: ImageInput
}

type ToolkitInput = {
  title?: string | null
  slug?: string | null
  type?: string | null
  description?: string | null
  access?: Toolkit['access'] | null
  coverStyle?: Toolkit['coverStyle'] | null
  fileUrl?: string | null
}

// Field helpers --------------------------------------------------------------

function toImage(src: ImageInput): ImageValue | undefined {
  if (!src?.asset) return undefined
  const {_id, _ref, url} = src.asset
  return {
    asset: {...(_id ? {_id} : {}), ...(_ref ? {_ref} : {}), ...(url ? {url} : {})},
    alt: src.alt
  }
}

function toPortableText(value: unknown): PortableTextBlock[] | undefined {
  return Array.isArray(value) && value.length ? (value as PortableTextBlock[]) : undefined
}

function toStats(src: Array<StatInput> | null | undefined): Stat[] | undefined {
  return src?.map((s) => ({value: s.value ?? '', numericValue: s.numericValue, suffix: s.suffix, label: s.label ?? '', note: s.note}))
}

function toPrinciples(src: Array<{title?: string; description?: string}> | null | undefined): Principle[] | undefined {
  return src?.map((p) => ({title: p.title ?? '', description: p.description ?? ''}))
}

function toSeo(src: SeoInput): SEO | undefined {
  if (!src) return undefined
  return {metaTitle: src.metaTitle, metaDescription: src.metaDescription, ogImage: toImage(src.ogImage), noIndex: src.noIndex}
}

// Entity mappers -------------------------------------------------------------

function toAuthor(src: AuthorInput): Author | undefined {
  if (!src) return undefined
  return {name: src.name ?? '', slug: src.slug ?? undefined, role: src.role ?? undefined, bio: src.bio ?? undefined, image: toImage(src.image)}
}

function toArticle(a: ArticleInput): Article {
  return {
    _id: a._id,
    title: a.title ?? '',
    slug: a.slug ?? '',
    excerpt: a.excerpt ?? '',
    category: a.category ?? '',
    format: a.format ?? undefined,
    publishedAt: a.publishedAt ?? '',
    readingTime: a.readingTime ?? undefined,
    image: toImage(a.image),
    author: toAuthor(a.author),
    body: toPortableText(a.body),
    externalVideoUrl: a.externalVideoUrl ?? undefined,
    featured: a.featured ?? undefined,
    tags: a.tags ?? undefined,
    relatedService: a.relatedService ? {title: a.relatedService.title ?? '', slug: a.relatedService.slug ?? ''} : undefined,
    seo: toSeo(a.seo)
  }
}

function toService(s: ServiceInput): Service {
  return {
    _id: s._id,
    title: s.title ?? '',
    slug: s.slug ?? '',
    eyebrow: s.eyebrow ?? '',
    intro: s.intro ?? '',
    body: s.body ?? '',
    image: toImage(s.image),
    deliverables: s.deliverables ?? [],
    outcomes: s.outcomes ?? [],
    seo: toSeo(s.seo)
  }
}

function toBrand(b: BrandInput): Brand {
  return {
    title: b.title ?? '',
    slug: b.slug ?? '',
    type: b.type ?? '',
    description: b.description ?? '',
    image: toImage(b.image),
    href: b.href ?? undefined,
    external: b.external ?? undefined
  }
}

function toToolkit(t: ToolkitInput): Toolkit {
  return {
    title: t.title ?? '',
    slug: t.slug ?? '',
    type: t.type ?? '',
    description: t.description ?? '',
    access: t.access ?? 'comingSoon',
    coverStyle: t.coverStyle ?? undefined,
    fileUrl: t.fileUrl ?? undefined
  }
}

// Loaders --------------------------------------------------------------------

export async function getSiteSettings(): Promise<SiteSettings> {
  const data = await sanityFetch<SITE_SETTINGS_QUERY_RESULT>(SITE_SETTINGS_QUERY)
  if (!data) return fallbackSettings
  return {
    title: data.title ?? fallbackSettings.title,
    tagline: data.tagline ?? fallbackSettings.tagline,
    description: data.description ?? fallbackSettings.description,
    email: data.email ?? fallbackSettings.email,
    phone: data.phone ?? fallbackSettings.phone,
    locations: data.locations ?? fallbackSettings.locations,
    logo: toImage(data.logo) ?? fallbackSettings.logo,
    socialLinks: data.socialLinks?.map((l) => ({platform: l.platform ?? '', url: l.url ?? ''})) ?? fallbackSettings.socialLinks,
    legalLinks: data.legalLinks?.map((l) => ({label: l.label ?? '', url: l.url ?? ''})) ?? fallbackSettings.legalLinks
  }
}

export async function getHomepage(): Promise<Homepage> {
  const data = await sanityFetch<HOMEPAGE_QUERY_RESULT>(HOMEPAGE_QUERY)
  if (!data) return fallbackHomepage
  const sectionOrder = (data.sections || [])
    .filter((x) => x.enabled !== false)
    .map((x) => x.sectionType)
    .filter((t): t is HomeSectionType => Boolean(t))
  const stats = toStats(data.stats)
  return {
    hero: {
      eyebrowLeft: data.heroEyebrowLeft || fallbackHomepage.hero.eyebrowLeft,
      eyebrowRight: data.heroEyebrowRight || fallbackHomepage.hero.eyebrowRight,
      titleBefore: data.heroTitleBefore || fallbackHomepage.hero.titleBefore,
      titleAccent: data.heroTitleAccent || fallbackHomepage.hero.titleAccent,
      identity: data.heroIdentity || fallbackHomepage.hero.identity,
      summary: data.heroSummary || fallbackHomepage.hero.summary,
      image: toImage(data.heroImage) || fallbackHomepage.hero.image,
      imageCaption: data.heroImageCaption || fallbackHomepage.hero.imageCaption,
      imageMeta: data.heroImageMeta || fallbackHomepage.hero.imageMeta,
      primaryCta: fallbackHomepage.hero.primaryCta,
      secondaryCta: fallbackHomepage.hero.secondaryCta
    },
    sectionOrder: sectionOrder.length ? sectionOrder : fallbackHomepage.sectionOrder,
    story: {
      heading: data.storyHeading || fallbackHomepage.story?.heading,
      opening: data.storyOpening || fallbackHomepage.story?.opening,
      body: toPortableText(data.storyBody) ?? fallbackHomepage.story?.body
    },
    stats: stats?.length ? stats : fallbackHomepage.stats,
    credibilityFacts: data.credibilityFacts?.length ? data.credibilityFacts.map((f) => ({label: f.label ?? '', title: f.title ?? ''})) : fallbackHomepage.credibilityFacts,
    publications: data.publications?.length ? data.publications : fallbackHomepage.publications,
    clientLogos: data.clientLogos?.length ? data.clientLogos.map((l) => ({name: l.name ?? '', image: toImage(l.image)})) : fallbackHomepage.clientLogos,
    featuredArticles: data.featuredArticles?.map(toArticle) ?? [],
    featuredServices: data.featuredServices?.map(toService) ?? [],
    featuredBrands: data.featuredBrands?.map(toBrand) ?? [],
    featuredToolkits: data.featuredToolkits?.map(toToolkit) ?? [],
    seo: toSeo(data.seo)
  }
}

export async function getServices(): Promise<Service[]> {
  const data = await sanityFetch<SERVICES_QUERY_RESULT>(SERVICES_QUERY)
  return data?.length ? data.map(toService) : fallbackServices
}

export async function getService(slug: string): Promise<Service | null> {
  const data = await sanityFetch<SERVICE_QUERY_RESULT>(SERVICE_QUERY, {slug})
  return data ? toService(data) : fallbackServices.find((service) => service.slug === slug) || null
}

export async function getArticles(): Promise<Article[]> {
  const data = await sanityFetch<ARTICLES_QUERY_RESULT>(ARTICLES_QUERY)
  return data?.length ? data.map(toArticle) : fallbackArticles
}

export async function getArticle(slug: string): Promise<Article | null> {
  const data = await sanityFetch<ARTICLE_QUERY_RESULT>(ARTICLE_QUERY, {slug})
  return data ? toArticle(data) : fallbackArticles.find((article) => article.slug === slug) || null
}

export async function getBrands(): Promise<Brand[]> {
  const data = await sanityFetch<BRANDS_QUERY_RESULT>(BRANDS_QUERY)
  return data?.length ? data.map(toBrand) : fallbackBrands
}

export async function getToolkits(): Promise<Toolkit[]> {
  const data = await sanityFetch<TOOLKITS_QUERY_RESULT>(TOOLKITS_QUERY)
  return data?.length ? data.map(toToolkit) : fallbackToolkits
}

export async function getAboutPage(): Promise<AboutPage | null> {
  const data = await sanityFetch<ABOUT_PAGE_QUERY_RESULT>(ABOUT_PAGE_QUERY)
  if (!data) return null
  return {
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    stats: toStats(data.stats),
    evolutionEyebrow: data.evolutionEyebrow ?? undefined,
    evolutionHeading: data.evolutionHeading ?? undefined,
    evolutionBody: toPortableText(data.evolutionBody),
    quote: data.quote ?? undefined,
    image: toImage(data.image),
    principlesEyebrow: data.principlesEyebrow ?? undefined,
    principlesHeading: data.principlesHeading ?? undefined,
    principlesIntro: data.principlesIntro ?? undefined,
    principles: toPrinciples(data.principles),
    seo: toSeo(data.seo)
  }
}

export async function getMembership(): Promise<MembershipPage | null> {
  const data = await sanityFetch<MEMBERSHIP_PAGE_QUERY_RESULT>(MEMBERSHIP_PAGE_QUERY)
  if (!data) return null
  return {
    comingSoonLabel: data.comingSoonLabel ?? undefined,
    heroTitle: data.heroTitle ?? undefined,
    heroAccent: data.heroAccent ?? undefined,
    intro: data.intro ?? undefined,
    benefitsEyebrow: data.benefitsEyebrow ?? undefined,
    benefitsHeading: data.benefitsHeading ?? undefined,
    benefitsIntro: data.benefitsIntro ?? undefined,
    benefits: toPrinciples(data.benefits),
    seo: toSeo(data.seo)
  }
}

export async function getFounder(): Promise<Founder | null> {
  const data = await sanityFetch<FOUNDER_QUERY_RESULT>(FOUNDER_QUERY)
  if (!data) return null
  return {
    name: data.name ?? undefined,
    headline: data.headline ?? undefined,
    intro: data.intro ?? undefined,
    image: toImage(data.image),
    body: toPortableText(data.body),
    belief: data.belief ?? undefined,
    stats: toStats(data.stats),
    statsNote: data.statsNote ?? undefined,
    publications: data.publications ?? undefined,
    roles: toPrinciples(data.roles),
    seo: toSeo(data.seo)
  }
}

export async function getMediaDesk(): Promise<MediaDesk | null> {
  const data = await sanityFetch<MEDIA_DESK_QUERY_RESULT>(MEDIA_DESK_QUERY)
  if (!data) return null
  return {
    headline: data.headline ?? undefined,
    intro: data.intro ?? undefined,
    requestTypes: toPrinciples(data.requestTypes),
    futureResources: toPrinciples(data.futureResources),
    seo: toSeo(data.seo)
  }
}

export async function getDiamondAwards(): Promise<DiamondAwards | null> {
  const data = await sanityFetch<DIAMOND_AWARDS_QUERY_RESULT>(DIAMOND_AWARDS_QUERY)
  if (!data) return null
  return {
    eventName: data.eventName ?? undefined,
    date: data.date ?? undefined,
    venue: data.venue ?? undefined,
    location: data.location ?? undefined,
    heroImage: toImage(data.heroImage),
    missionPoints: data.missionPoints ?? undefined,
    audience: data.audience ?? undefined,
    eventExperience: data.eventExperience ?? undefined,
    sponsorBenefits: data.sponsorBenefits ?? undefined,
    sponsorshipPackages: data.sponsorshipPackages?.map((p) => ({tier: p.tier, name: p.name ?? '', description: p.description, features: p.features})),
    contactEmail: data.contactEmail ?? undefined,
    contactPhoneUae: data.contactPhoneUae ?? undefined,
    contactPhoneUk: data.contactPhoneUk ?? undefined,
    seo: toSeo(data.seo)
  }
}
