import {NewsletterBand, PageHero} from '@/components/CommonSections'
import {getToolkits} from '@/lib/content'
import {createMetadata} from '@/lib/metadata'

export const metadata = createMetadata('Toolkits', 'Downloadable guides, templates, reports and practical resources for aesthetics professionals and brands.', undefined, '/toolkits')

export default async function ToolkitsPage() {
  const toolkits = await getToolkits()
  return <div className="page-enter"><PageHero title="Knowledge you can" accent="put to work." intro="Downloadable guides, templates, reports and practical resources for ambitious aesthetics professionals and brands." crumbs={[{label: 'Home', href: '/'}, {label: 'Toolkits'}]} /><section><div className="shell"><div className="filter-bar">{['All resources', 'Reports', 'Guides', 'Templates', 'Member resources'].map((label, index) => <button className={`filter-chip ${index === 0 ? 'active' : ''}`} key={label}>{label}</button>)}</div><div className="toolkit-grid">{toolkits.map((toolkit) => <article className="toolkit-card" key={toolkit.slug}><div className={`toolkit-cover ${toolkit.coverStyle === 'pink' ? 'pink-cover' : toolkit.coverStyle === 'dark' ? 'dark-cover' : ''}`}><span className="doc">CMG / {toolkit.type}</span><h3>{toolkit.title}</h3></div><div className="toolkit-info"><div className="locked">{toolkit.access === 'members' ? '◉ Members only' : toolkit.access === 'paid' ? 'Paid resource' : '↓ Free download'}</div><p>{toolkit.description}</p>{toolkit.access === 'members' ? <a className="text-link" href="/membership">View membership ↗</a> : toolkit.fileUrl ? <a className="text-link" href={toolkit.fileUrl}>Download resource ↗</a> : <span className="text-link">Download resource ↗</span>}</div></article>)}</div></div></section><section className="dark-section"><div className="shell two-col"><div><div className="eyebrow">Research & industry insight</div><h2 style={{fontSize: 60, lineHeight: .97, letterSpacing: '-.05em'}}>Original intelligence for a fast-moving industry.</h2></div><div><p style={{color: '#bdb7b3', fontSize: 18, lineHeight: 1.7}}>Annual editorial guides and research reports will bring together data, expert views and emerging trends — highlighting excellence and helping the industry make better-informed decisions.</p><a className="btn btn-white" href="/membership">Explore future membership ↗</a></div></div></section><NewsletterBand /></div>
}
