import Image from 'next/image'
import Link from 'next/link'
import {getDiamondAwards} from '@/lib/content'
import {createMetadata} from '@/lib/metadata'
import {imageUrl} from '@/sanity/lib/image'
import type {SponsorshipPackage} from '@/types'

const FALLBACK_PACKAGES: SponsorshipPackage[] = [
  {tier: 'Premier partnership', name: 'Diamond', description: 'Maximum prominence across the complete awards platform and event experience.', features: ['Headline and category opportunities', 'High-profile stage and room visibility', 'Integrated media, content and PR exposure', 'Exclusive activation possibilities']},
  {tier: 'High-impact partnership', name: 'Gold', description: 'Strong brand presence with meaningful access to attendees and industry channels.', features: ['Category and activation options', 'Digital and campaign inclusion', 'VIP attendance and networking', 'Brand alignment with excellence']},
  {tier: 'Focused partnership', name: 'Silver', description: 'Targeted visibility through selected event, media or gifting opportunities.', features: ['Table, talent or media partnerships', 'Gift bag and technology options', 'Selected campaign inclusion', 'Flexible category alignment']}
]

export async function generateMetadata() {
  const data = await getDiamondAwards()
  return createMetadata('The Diamond Awards Dubai 2027', 'Celebrating excellence and elevating standards across the aesthetics industry.', data?.seo, '/diamond-awards')
}

export default async function DiamondAwardsPage() {
  const data = await getDiamondAwards()
  const hero = data?.heroImage || '/images/diamond1.jpg'
  const eventDate = data?.date ? new Date(`${data.date}T12:00:00`).toLocaleDateString('en-GB', {weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'}) : 'Saturday 10th April 2027'
  const venue = data?.venue || 'Atlantis The Royal'
  const location = data?.location || 'Palm Jumeirah'
  const missionPoints = data?.missionPoints || [
    'Recognise the highest standards of clinical safety, professionalism and patient care.',
    'Highlight innovators in technology, devices, products and treatment protocols.',
    'Elevate the region’s reputation as a leader in aesthetics excellence.',
    'Bring the global industry together through a prestigious annual event in Dubai.'
  ]
  const audience = data?.audience || ['Leading dermatologists and plastic surgeons', 'Aesthetic physicians and practitioners', 'Clinic owners, directors and practice managers', 'Device manufacturers and technology innovators', 'Skincare brands and product formulators', 'Industry educators, regulatory voices, press and VIP guests']
  const packages = data?.sponsorshipPackages?.length ? data.sponsorshipPackages : FALLBACK_PACKAGES
  return <div className="page-enter diamond-page">
    <section className="da-hero"><Image src={imageUrl(hero, 1800, 1100)} alt="The Diamond Awards Dubai 2027" width={1800} height={1100} priority sizes="100vw" /><div className="shell da-hero-content"><div className="da-hero-top"><span>{venue}, {location}</span><span>{eventDate}</span></div><div className="da-hero-copy"><div className="kicker">The first ever Dubai edition</div><h1>{data?.eventName || 'The Diamond Awards Dubai'}</h1><p>Celebrating excellence. Elevating standards. Bringing the global aesthetics industry together in one of the world’s most ambitious cities.</p><div className="da-hero-actions"><Link className="btn btn-da" href="/contact">Sponsorship opportunities ↗</Link><a className="btn btn-da-ghost" href={`mailto:${data?.contactEmail || 'lucy@cosmeticpr.com'}?subject=Diamond%20Awards%20Dubai%202027`}>Register interest ↗</a></div></div></div></section>

    <section className="da-story"><div className="shell da-story-grid"><div className="da-visual"><Image src="/images/diamond2.jpg" alt="A legacy of excellence" width={1000} height={800} sizes="(max-width: 980px) 100vw, 50vw" /></div><div className="da-copy"><div className="da-index">01 — Our history</div><h2>A legacy of excellence. A new chapter in Dubai.</h2><p>Established in the UK in 2013, The Diamond Awards were created with one clear purpose: to champion safety, ethics and excellence within the global aesthetics and beauty industry.</p><p>Over the past decade, the Awards have grown into one of the sector’s most respected and influential platforms, recognising the clinics, practitioners, brands and innovators who go above and beyond.</p><p>Now, for the first time, this internationally recognised platform comes to Dubai, a city synonymous with innovation, luxury and world-class aesthetic standards.</p></div></div></section>

    <section className="da-statement"><div className="shell da-statement-grid"><div><div className="da-index">02 — Our mission</div><h2>Raising global standards. Celebrating those who lead the way.</h2><p>At its core, this platform exists to protect, celebrate and elevate the aesthetic industry. Dubai is the perfect home for its next chapter.</p><div className="da-bullets">{missionPoints.map((point: string, index: number) => <div className="da-bullet" key={point}><b>{String(index + 1).padStart(2, '0')}</b><span>{point}</span></div>)}</div></div><div className="da-statement-visual"><Image src="/images/diamond3.jpg" alt="The Diamond Awards mission" width={1000} height={1000} sizes="(max-width: 980px) 100vw, 50vw" /></div></div></section>

    <section className="da-story"><div className="shell da-story-grid"><div className="da-copy"><div className="da-index">03 — Why Dubai</div><h2>A global hub for aesthetic innovation.</h2><p>Dubai has become one of the fastest-growing and most influential centres for aesthetic medicine worldwide, with world-leading clinics and practitioners, a thriving medical tourism market, strong regulatory frameworks and unmatched demand for premium treatments.</p><p>Launching The Diamond Awards in Dubai positions the region at the forefront of aesthetic excellence, giving brands and clinics the international recognition they deserve.</p></div><div className="da-visual"><Image src="/images/diamond4.jpg" alt="Dubai aesthetic innovation" width={1000} height={800} sizes="(max-width: 980px) 100vw, 50vw" /></div></div></section>

    <section className="da-principles"><div className="shell"><div className="da-principles-head"><div><div className="da-index">04 — About the awards</div><h2>A trusted, respected and independent platform.</h2></div><p>The Dubai edition will combine a decade-long reputation for integrity with new categories tailored to the Middle Eastern market, including devices, energy-based technologies, advanced skincare, luxury clinics and practitioner achievement.</p></div><div className="da-principles-grid"><div className="da-principle"><span>01</span><div><h3>Transparent judging</h3><p>A clear scoring system led by respected experts with genuine category knowledge.</p></div></div><div className="da-principle"><span>02</span><div><h3>Integrity & credibility</h3><p>A decade-long UK reputation for fairness, independence and excellence.</p></div></div><div className="da-principle"><span>03</span><div><h3>Global recognition</h3><p>Powerful international exposure and trust for finalists, winners and partners.</p></div></div><div className="da-principle"><span>04</span><div><h3>Results & responsibility</h3><p>Recognition for outcomes, ethical practice, safety protocols and patient experience.</p></div></div></div></div></section>

    <section className="da-sponsor"><div className="shell"><div className="da-sponsor-hero"><Image src="/images/diamond6.jpg" alt="Diamond Awards sponsorship opportunity" width={1000} height={1000} sizes="(max-width: 980px) 100vw, 50vw" /><div className="da-sponsor-copy"><div className="da-index">05 — Sponsor the first Dubai edition</div><h2>Visibility. Credibility. Influence.</h2><p>Becoming a sponsor offers brands unparalleled access to the region’s most respected leaders in aesthetics and a milestone platform with long-term growth potential.</p><div className="da-sponsor-benefits">{(data?.sponsorBenefits || ['Brand positioning alongside global excellence', 'Exposure across GCC press, media and industry channels', 'Access to clinic owners, dermatologists, surgeons and leaders', 'On-stage and in-room visibility at a high-profile gala', 'Inclusion in marketing, digital and PR campaigns', 'Exclusive partnership rights within your category']).map((item: string) => <div key={item}>{item}</div>)}</div></div></div></div></section>

    <section className="da-audience"><div className="shell da-audience-grid"><div><div className="da-index">06 — Who attends</div><h2>The industry’s most influential decision makers.</h2></div><div className="da-audience-list">{audience.map((item: string, index: number) => <div key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span></div>)}</div></div></section>

    <section className="da-experience"><div className="shell da-experience-grid"><div className="da-experience-image"><Image src="/images/diamond8.jpg" alt="Atlantis The Royal Diamond Awards event experience" width={1000} height={800} sizes="(max-width: 980px) 100vw, 50vw" /></div><div><div className="da-index">07 — Event experience</div><h2>A night of prestige and celebration.</h2><p>Hosted at Atlantis The Royal, one of Dubai’s most sought-after venues, the event will reflect the sophistication and innovation of the region’s aesthetic landscape.</p><div className="da-experience-list">{(data?.eventExperience || ['Luxury gala dinner', 'Live entertainment', 'Awards presentations', 'Red carpet arrivals', 'Press interviews and media coverage', 'Premium brand activations', 'Regional and global networking', 'World-class hospitality']).map((item: string) => <span key={item}>{item}</span>)}</div></div></div></section>

    <section className="da-packages"><div className="shell"><div className="da-packages-head"><h2>Sponsorship packages.</h2><p>A curated range of partnership opportunities, each tailored to maximise visibility, engagement and alignment with excellence.</p></div><div className="da-package-grid">{packages.map((pkg) => <div className="da-package" key={pkg.name}><div>{pkg.tier && <small>{pkg.tier}</small>}<h3>{pkg.name}</h3>{pkg.description && <p>{pkg.description}</p>}</div>{pkg.features?.length ? <ul>{pkg.features.map((feature) => <li key={feature}>{feature}</li>)}</ul> : null}</div>)}</div></div></section>

    <section className="da-contact"><div className="shell"><div className="da-contact-card"><Image src="/images/diamond10.jpg" alt="Be part of the first ever Dubai edition" width={1000} height={1000} sizes="(max-width: 980px) 100vw, 45vw" /><div className="da-contact-copy"><div className="da-index">08 — Partner with us</div><h2>Be part of the first ever Dubai edition.</h2><p>The launch of The Diamond Awards in Dubai marks a major milestone for the global aesthetics industry. Join the clinics, practitioners and brands continuing to push the industry forward.</p><div className="da-contact-links"><a href={`https://wa.me/${(data?.contactPhoneUae || '+971 58 582 7507').replace(/\D/g, '')}`} target="_blank" rel="noreferrer"><span>UAE WhatsApp</span><b>{data?.contactPhoneUae || '+971 58 582 7507'} ↗</b></a><a href={`https://wa.me/${(data?.contactPhoneUk || '+44 7958 429 130').replace(/\D/g, '')}`} target="_blank" rel="noreferrer"><span>UK WhatsApp</span><b>{data?.contactPhoneUk || '+44 7958 429 130'} ↗</b></a><a href={`mailto:${data?.contactEmail || 'lucy@cosmeticpr.com'}?subject=Diamond%20Awards%20Dubai%202027%20Sponsorship`}><span>Email Lucy Hilson</span><b>{data?.contactEmail || 'lucy@cosmeticpr.com'} ↗</b></a></div><a className="btn btn-da" href={`mailto:${data?.contactEmail || 'lucy@cosmeticpr.com'}?subject=Diamond%20Awards%20Dubai%202027%20Rates%20Card`}>Request the rates card ↗</a></div></div></div></section>

    <section className="da-signoff"><div className="shell"><p>Celebrating excellence · Elevating standards</p><h2>Empowering the future of aesthetics in the Middle East.</h2><Link className="btn btn-da" href="/">Return to Cosmetic Media Group ↗</Link></div></section>
  </div>
}
