import type {QueryParams} from 'next-sanity'
import {client} from './client'
import {isSanityConfigured} from '../env'

/**
 * Thin wrapper around the Sanity client that returns `null` (instead of throwing)
 * when Sanity is not configured or a request fails, so callers can fall back to
 * local content. Callers pass the matching `*_QUERY_RESULT` type generated by
 * Sanity TypeGen (`sanity.types.ts`) so results are typed against the schema.
 */
export async function sanityFetch<T>(query: string, params: QueryParams = {}): Promise<T | null> {
  if (!isSanityConfigured) return null
  try {
    return await client.fetch<T>(query, params, {next: {revalidate: 60}})
  } catch (error) {
    console.error('Sanity fetch failed:', error)
    return null
  }
}
